### ISSUE TITLE
`compress` command doesn't acknowledge non-default compression type(gz, lz4, bzip2)

### ISSUE THREAD

**Issue by shikharish** [pgmoneta/pgmoneta#444]
The `compress` command seems to ignore the `-C` flag.

I ran pgmoneta in offline mode:
```
❯ ./pgmoneta -c pgmoneta.conf -u pgmoneta_users.conf --offline
```
 And compress command:
```
❯ ./pgmoneta-cli -c pgmoneta.conf compress text -C gz
```

Info says the compression is gzip, but the compressed file is .zstd
```
Header: 
  ClientVersion: 0.16.0
  Command: compress
  Compression: gzip
  Encryption: none
  Output: text
  Timestamp: 20241231024353
Outcome: 
  Status: true
  Time: 00:00:0.0044
Request: 
  SourceFile: text
Response: 
  DestinationFile: text.zstd
  ServerVersion: 0.16.0
```

Logs:
```
2024-12-31 02:43:53 DEBUG main.c:839 Management 17: {
  "Header": {
    "ClientVersion": "0.16.0",
    "Command": 17,
    "Compression": 1,
    "Encryption": 0,
    "Output": 0,
    "Timestamp": "20241231024353"
  },
  "Request": {
    "SourceFile": "text"
  }
}
2024-12-31 02:43:53 INFO  zstandard_compression.c:658 ZSTD: text (Elapsed: 00:00:0.0044)
```
