### ISSUE TITLE
pgmoneta-admin: Memory leak

### ISSUE THREAD

**Issue by Mohab96** [pgmoneta/pgmoneta#632]
Memory leak is happening on the latest commit on the main branch when I try to run the test suite.

```
➜  build git:(main) ./testsuite.sh
Check System Requirements 
check system os ... Linux
check initdb in path ... ok
check pg_ctl in path ... ok
check psql in path ... ok
check postgresql version: 17.4 ... ok

Initialize Test logfiles 
create log directory ... /home/mohab/Documents/Coding/Projects/pgmoneta/build/log
create log file ... /home/mohab/Documents/Coding/Projects/pgmoneta/build/log/pgmoneta.log
create log file ... /home/mohab/Documents/Coding/Projects/pgmoneta/build/log/logfile

Initializing Cluster 
/home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-postgresql/data
The files belonging to this database system will be owned by user "mohab".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

creating directory /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default "max_connections" ... 100
selecting default "shared_buffers" ... 128MB
selecting default time zone ... Africa/Cairo
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/17/bin/pg_ctl -D /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-postgresql/data -l logfile start

initdb exit code: 0
initialize database ... ok
setting postgresql.conf
setting password_encryption ... scram-sha-256
setting unix_socket_directories ... '/tmp'
setting shared_buffers ... 2GB
setting port ... 5433
setting max_prepared_transactions ... 100
setting work_mem ... 16MB
setting wal_level ... replica
setting wal_log_hints ... on
setting max_wal_size ... 16GB
setting min_wal_size ... 2GB
setting summarize_wal ... on

Create HBA Configuration 
initialize hba configuration at /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-postgresql/data/pg_hba.conf ... ok

Initializing Cluster 
waiting for server to start.... done
server started
localhost:5433 - accepting connections
postgres server is accepting requests ... ok
create role repl ... ok
create replication slot for repl ... ok
create user myuser ... ok
create database mydb with owner myuser ... ok
waiting for server to shut down.... done
server stopped

Initialize pgmoneta configuration files 
create restore directory /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-testsuite/restore ... ok
create configuration directory /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-testsuite/conf ... ok
create pgmoneta.conf and pgmoneta_users.conf inside /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-testsuite/conf ... ok
add test configuration to pgmoneta.conf ... ok
pgmoneta-admin: The file ~/.pgmoneta/master.key already exists
Header:
  ClientVersion: 0.17.0
  Command: 24
  Compression: 0
  Encryption: 0
  Output: 0
  Timestamp: 20250511070635
Outcome:
  Error: 1
  Status: false
  Workflow: admin
pgmoneta-admin: Cannot generate master key

=================================================================
==166971==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0x589d29e4e780 in realloc (/home/mohab/Documents/Coding/Projects/pgmoneta/build/src/pgmoneta-admin+0xcc780) (BuildId: 018270af1c58e63ba3664f5a7538879e3929763d)
    #1 0x71e00d0b05f2 in argz_add_sep string/argz-addsep.c:34:24
    #2 0x71e00d039bdb in __newlocale locale/newlocale.c:111:11
    #3 0x71e00c3658fc in p11_library_init_impl /usr/src/p11-kit-0.25.3-4ubuntu2.1/common/library.c:165:23
    #4 0x71e00e49d71e in call_init elf/dl-init.c:74:3
    #5 0x71e00e49d823 in call_init elf/dl-init.c:120:14
    #6 0x71e00e49d823 in _dl_init elf/dl-init.c:121:5
    #7 0x71e00e4b759f  (/lib64/ld-linux-x86-64.so.2+0x1f59f) (BuildId: 1c8db5f83bba514f8fd5f1fb6d7be975be1bb855)

SUMMARY: AddressSanitizer: 46 byte(s) leaked in 1 allocation(s).
Header:
  ClientVersion: 0.17.0
  Command: 25
  Compression: 0
  Encryption: 0
  Output: 0
  Timestamp: 20250511070635
Outcome:
  Status: true
  Time: 00:00:0.0073
Response:
  Users:
    - repl

=================================================================
==166987==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0x59cc0897e780 in realloc (/home/mohab/Documents/Coding/Projects/pgmoneta/build/src/pgmoneta-admin+0xcc780) (BuildId: 018270af1c58e63ba3664f5a7538879e3929763d)
    #1 0x7231dcab05f2 in argz_add_sep string/argz-addsep.c:34:24
    #2 0x7231dca39bdb in __newlocale locale/newlocale.c:111:11
    #3 0x7231dbd658fc in p11_library_init_impl /usr/src/p11-kit-0.25.3-4ubuntu2.1/common/library.c:165:23
    #4 0x7231dde8571e in call_init elf/dl-init.c:74:3
    #5 0x7231dde85823 in call_init elf/dl-init.c:120:14
    #6 0x7231dde85823 in _dl_init elf/dl-init.c:121:5
    #7 0x7231dde9f59f  (/lib64/ld-linux-x86-64.so.2+0x1f59f) (BuildId: 1c8db5f83bba514f8fd5f1fb6d7be975be1bb855)

SUMMARY: AddressSanitizer: 46 byte(s) leaked in 1 allocation(s).
➜  build git:(main) 
```

**Comment by Mohab96** [comment]
I am talking about this commit https://github.com/pgmoneta/pgmoneta/commit/cbcd608a9d8e831061a94cf887c9babcde2f905f

**Comment by Mohab96** [comment]
After removing `~/.pgmoneta/master.key`, this is the output
```
Initialize pgmoneta configuration files 
create restore directory /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-testsuite/restore ... ok
create configuration directory /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-testsuite/conf ... ok
create pgmoneta.conf and pgmoneta_users.conf inside /home/mohab/Documents/Coding/Projects/pgmoneta/build/pgmoneta-testsuite/conf ... ok
add test configuration to pgmoneta.conf ... ok
Header:
  ClientVersion: 0.16.0
  Command: 24
  Compression: 0
  Encryption: 0
  Output: 0
  Timestamp: 20250511072221
Outcome:
  Status: true
  Time: 00:00:0.0009

=================================================================
==178982==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0x6038dbca1780 in realloc (/home/mohab/Documents/Coding/Projects/pgmoneta/build/src/pgmoneta-admin+0xcc780) (BuildId: b979bf98a7c67d990e4ff730fa9c1894eddb88f7)
    #1 0x7d7316cb05f2 in argz_add_sep string/argz-addsep.c:34:24
    #2 0x7d7316c39bdb in __newlocale locale/newlocale.c:111:11
    #3 0x7d7315f658fc in p11_library_init_impl /usr/src/p11-kit-0.25.3-4ubuntu2.1/common/library.c:165:23
    #4 0x7d7317fd971e in call_init elf/dl-init.c:74:3
    #5 0x7d7317fd9823 in call_init elf/dl-init.c:120:14
    #6 0x7d7317fd9823 in _dl_init elf/dl-init.c:121:5
    #7 0x7d7317ff359f  (/lib64/ld-linux-x86-64.so.2+0x1f59f) (BuildId: 1c8db5f83bba514f8fd5f1fb6d7be975be1bb855)

SUMMARY: AddressSanitizer: 46 byte(s) leaked in 1 allocation(s).
Header:
  ClientVersion: 0.16.0
  Command: 25
  Compression: 0
  Encryption: 0
  Output: 0
  Timestamp: 20250511072221
Outcome:
  Status: true
  Time: 00:00:0.0075
Response:
  Users:
    - repl

=================================================================
==178986==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0x63fb36d87780 in realloc (/home/mohab/Documents/Coding/Projects/pgmoneta/build/src/pgmoneta-admin+0xcc780) (BuildId: b979bf98a7c67d990e4ff730fa9c1894eddb88f7)
    #1 0x78b7678b05f2 in argz_add_sep string/argz-addsep.c:34:24
    #2 0x78b767839bdb in __newlocale locale/newlocale.c:111:11
    #3 0x78b766b658fc in p11_library_init_impl /usr/src/p11-kit-0.25.3-4ubuntu2.1/common/library.c:165:23
    #4 0x78b768cf671e in call_init elf/dl-init.c:74:3
    #5 0x78b768cf6823 in call_init elf/dl-init.c:120:14
    #6 0x78b768cf6823 in _dl_init elf/dl-init.c:121:5
    #7 0x78b768d1059f  (/lib64/ld-linux-x86-64.so.2+0x1f59f) (BuildId: 1c8db5f83bba514f8fd5f1fb6d7be975be1bb855)

SUMMARY: AddressSanitizer: 46 byte(s) leaked in 1 allocation(s).
➜  build git:(wal-testing) 
```
