### ISSUE TITLE
Implement YAML Parser for pgmoneta-walfilter

### ISSUE THREAD

**Issue by Mohab96** [pgmoneta/pgmoneta#671]
# Description
This issue tracks the development of a YAML parser for the pgmoneta-walfilter tool to read and interpret a YAML configuration file specifying filtering criteria. The parser will initially support criteria for excluding DELETE operations, with a modular design to accommodate future criteria.

# Tasks

- Implement a function to read the YAML file and parse its contents into a C struct.
- Create an internal data structure to store parsed criteria for use by the WAL filtering logic.

# YAML Schema Example

```yaml
backup_dir: /path/to/backup
target_dir: /dir/with/new/wal/stream

rules:
  - exclude: # open to add 'include' in the future
    - operations: [ DELETE ]
```
